version: '3.7'

services:
  # main:
  #   container_name: main
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - ${SERVER_PORT}:${SERVER_PORT}
  #   env_file:
  #     - .env
  #   networks:
  #     - webnet
  #   depends_on:
  #     - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    # networks:
    # - webnet
    environment:
      POSTGRES_PASSWORD: Aa1234567
      POSTGRES_USER: postgres
      POSTGRES_DB: truthy
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'
    container_name: redis
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./volumes/redis/data:/data
    env_file:
      - .env
    ports:
      - 6379:6379
# networks:
#   webnet:
#     driver: bridge
# volumes:
#   pgdata:
