@PORT=7777
@JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJodHRwOi8vbG9jYWxob3N0Ojc3NzciLCJhdWRpZW5jZSI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsInN1YmplY3QiOiIxIiwiaXNUd29GQUF1dGhlbnRpY2F0ZWQiOmZhbHNlLCJpYXQiOjE2NTg4MzI0MTcsImV4cCI6MTY1ODgzMzMxN30.93tY8wkHgHQb0DIw09g9NAeZ3adr3dZBSmMF6L8g9kY; HttpOnly; Path=/;  Max-Age=604800,Refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJodHRwOi8vbG9jYWxob3N0Ojc3NzciLCJhdWRpZW5jZSI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImV4cGlyZXNJbiI6NjA0ODAwLCJzdWJqZWN0IjoiMSIsImp3dGlkIjoiMSIsImlhdCI6MTY1ODgzMjQxNywiZXhwIjoxNjU4ODMzMzE3fQ.V-QrazRGVLDCIKPikpguzC_K0pbjWR-Qdhdw63HT6ng

GET http://localhost:{{PORT}}

###
POST http://localhost/api/auth/login
content-type: application/json

{
    "username": "admin@truthy.com",
    "password": "Truthy@123",
    "remember":true
}

###
POST http://localhost:{{PORT}}/auth/login
content-type: application/json

{
    "username": "admin@truthy.com",
    "password": "Truthy@123",
    "remember":true
}

###
GET http://localhost:{{PORT}}/auth/token-info
Authorization: Bearer {{JWT}}


###
GET http://localhost:{{PORT}}/users/1
Authorization: Bearer {{JWT}}

###
GET http://localhost:{{PORT}}/users
Authorization: Bearer {{JWT}}
