@PORT=7777
@JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJodHRwOi8vbG9jYWxob3N0Ojc3NzciLCJhdWRpZW5jZSI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsInN1YmplY3QiOiIxIiwiaXNUd29GQUF1dGhlbnRpY2F0ZWQiOmZhbHNlLCJpYXQiOjE2NTg4MjMzMTMsImV4cCI6MTY1ODgyNDIxM30.5DZUtaR_gaUqdzsmGPgQGaBjnKuI-gYlkreFJf-1Ccc

GET http://localhost:{{PORT}}

###
POST http://localhost:{{PORT}}/auth/login
content-type: application/json

{
    "username": "admin@truthy.com",
    "password": "Truthy@123",
    "remember":true
}

###
GET http://localhost:{{PORT}}/auth/token-info
Authorization: Bearer {{JWT}}


###
GET http://localhost:{{PORT}}/users/1
Authorization: Bearer {{JWT}}

###
GET http://localhost:{{PORT}}/users
Authorization: Bearer {{JWT}}
